Ignore interrupted syscall on poll
Most of Captain Comeback's time is spent waiting on an epoll fd to wake
up. Unfortunately, if we interrupt that wait (e.g. by tracing Captain
Comeback), then Captain Comeback will crash due to an interrupted system
call:

```
Traceback (most recent call last):
  File "/usr/local/bin/captain-comeback", line 11, in <module>
    load_entry_point('captain-comeback==0.1.0', 'console_scripts',
'captain-comeback')()
  File "/usr/local/lib/python2.7/dist-packages/captain_comeback/cli.py",
line 141, in cli_entrypoint
    sys.exit(main_wrapper(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/captain_comeback/cli.py",
line 137, in main_wrapper
    restart_grace_period)
  File "/usr/local/lib/python2.7/dist-packages/captain_comeback/cli.py",
line 64, in run_loop
    index.poll(poll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/captain_comeback/index.py",
line 74, in poll
    events = self.epl.poll(timeout)
IOError: [Errno 4] Interrupted system call
```

In practice, that's not a real problem in production since Upstart will
automatically restart Captain Comeback and it'll recover just fine.
However, that means we can't easily trace Captain Comeback, which is a
little unfortunate / annoying.

This patch fixes that problem by ignoring this particular error when
polling (we'll re-enter the poll loop practically immediately anyway).